---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: v1.9.7
  name: kube-state-metrics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
