---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: v1.9.7
    monitoring: "true"
  name: kube-state-metrics
spec:
  clusterIP: None
  ports:
  - name: https-main
    port: 8443
    targetPort: https-main
  - name: https-self
    port: 9443
    targetPort: https-self
  selector:
    app.kubernetes.io/name: kube-state-metrics
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-example-app
    monitoring: "true"
  name: prometheus-example-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: web
  selector:
    app: promethe
---
apiVersion: v1
kind: Service
metadata:
  name: example-monitoring-app
  namespace: {{ .Values.monitoring_namespace }}
  labels:
    app: example-monitoring-app
    service: example-monitoring-app
    monitoring: "true"
spec:
  ports:
  - port: 8080
    name: web
    targetPort: 8080
  selector:
    app: example-monitoring-app
